"""Single source of truth for every research/validation number shown in the app.

Loads `data/research_results.json` (generated by `generate_research_results.py`
from the validated `data/model_metrics.csv`, `data/repeated_split_summary.csv`, and
the fitted `.pkl` feature importances — never hand-edited) and exposes typed
accessors. Every page must read MAE/AIC/coefficient/feature-importance/alpha
numbers through this module; no other module in the app should contain a
research-number-shaped float literal as the value actually displayed.

Example values (for reference only — NOT used as fallbacks/defaults, always read
live from the JSON): Poisson MAE 0.09888 / AIC 229548.83; NB2 MAE 0.09944 / AIC
228839.46 / alpha 0.98456; Random Forest MAE 0.09809, wins 18/20 repeated splits.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import streamlit as st

_DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "research_results.json"

# Canonical display order used by every table/chart in the app.
MODEL_ORDER = ["poisson", "negative_binomial", "random_forest", "xgboost"]

_Z_95 = 1.959963985  # two-sided 95% normal critical value, used only to derive a CI
                      # from alpha/alpha_se already present in the JSON — not a
                      # research value in itself.


@st.cache_data(show_spinner=False)
def load_research_results() -> dict:
    """Load the research-results JSON once per session (cached)."""
    with open(_DATA_PATH, "r") as f:
        return json.load(f)


def get_dataset_info() -> dict:
    return load_research_results()["dataset"]


def get_model(key: str) -> dict:
    """Raw per-model block (key in MODEL_ORDER)."""
    return load_research_results()["models"][key]


def get_model_metrics(as_dataframe: bool = False):
    """Per-model primary-split summary: key, display_name, model_type, mae, aic, strength."""
    models = load_research_results()["models"]
    rows = []
    for key in MODEL_ORDER:
        m = models[key]
        ps = m["primary_split"]
        rows.append({
            "key": key,
            "display_name": m["display_name"],
            "model_type": m["model_type"],
            "mae": ps["mae"],
            "aic": ps.get("aic"),
            "strength": m["main_strength"],
        })
    return pd.DataFrame(rows) if as_dataframe else rows


def get_repeated_split_summary(as_dataframe: bool = False):
    """20-split repeated-validation summary per model: mean/std MAE, 95% CI,
    win count / win %, and average rank."""
    models = load_research_results()["models"]
    rows = []
    for key in MODEL_ORDER:
        rs = models[key]["repeated_split"]
        rows.append({
            "key": key,
            "display_name": models[key]["display_name"],
            "model_type": models[key]["model_type"],
            "n_splits": rs["n_splits"],
            "mean_mae": rs["mean_mae"],
            "std_mae": rs["std_mae"],
            "ci95_low": rs["ci95_low"],
            "ci95_high": rs["ci95_high"],
            "n_wins": rs["n_wins"],
            "pct_wins": rs["pct_wins"],
            "avg_rank": rs["avg_rank"],
        })
    return pd.DataFrame(rows) if as_dataframe else rows


def get_feature_importance(model_key: str) -> dict:
    """model_key: 'random_forest' or 'xgboost'. Extracted live from the fitted
    model at generation time — never hand-copied."""
    return get_model(model_key).get("feature_importance", {})


def get_poisson_info() -> dict:
    ps = get_model("poisson")["primary_split"]
    return {
        "mae": ps.get("mae"),
        "aic": ps.get("aic"),
        "log_likelihood": ps.get("log_likelihood"),
        "k_params": ps.get("k_params"),
        "coefficients": ps.get("coefficients", {}),
    }


def get_nb2_info() -> dict:
    """NB2 (alpha estimated via MLE) production spec, plus the superseded
    fixed-alpha=1 comparison and a derived 95% CI for alpha (alpha ± 1.96*SE —
    both alpha and its SE come straight from the JSON, only the CI arithmetic is
    computed here)."""
    nb = get_model("negative_binomial")
    ps = nb["primary_split"]
    alpha, alpha_se = ps.get("alpha"), ps.get("alpha_se")
    ci_low = ci_high = None
    if alpha is not None and alpha_se is not None:
        ci_low = alpha - _Z_95 * alpha_se
        ci_high = alpha + _Z_95 * alpha_se
    return {
        "mae": ps.get("mae"),
        "aic": ps.get("aic"),
        "log_likelihood": ps.get("log_likelihood"),
        "k_params": ps.get("k_params"),
        "alpha": alpha,
        "alpha_se": alpha_se,
        "alpha_ci95_low": ci_low,
        "alpha_ci95_high": ci_high,
        "coefficients": ps.get("coefficients", {}),
        "prior_fixed_alpha_comparison": nb.get("prior_fixed_alpha_comparison", {}),
    }


def get_cross_model() -> dict:
    """Cross-model findings: top predictor, AIC delta (NB2 vs Poisson), the
    predictive-ceiling note, and which model wins the repeated-split comparison."""
    return load_research_results()["cross_model"]


def get_best_mae_model() -> dict:
    """Model with the lowest primary-split MAE — replaces the old
    `mae == 0.09809` float-equality "best row" check with an actual comparison."""
    return min(get_model_metrics(), key=lambda r: r["mae"])


def get_best_repeated_split_model() -> dict:
    """Model with the best (lowest) average rank across the 20 repeated splits."""
    return min(get_repeated_split_summary(), key=lambda r: r["avg_rank"])
